title: HI, I AM
logo: /assets/a_photo_of_prada.pnghatsApp Image 2024-08-21 at 4.36.48 PM (1).jpeg
description: A Linux Enthusiast and a ReactJS FrontEnd Web Developer, in 💖 with Python and Large Language Models.
show_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
